dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.3.1
  #- nomiclabs/hardhat/packages/hardhat-core@2.8.3
  - OpenZeppelin/openzeppelin-contracts@4.4.2
compiler:
  solc:
    remappings:
      - '@chainlink-brownie-contracts=smartcontractkit/chainlink-brownie-contracts@0.3.1'
      #- '@hardhat=nomiclabs/hardhat/packages/hardhat-core@2.8.3'
      - '@openzeppelin-contracts=OpenZeppelin/openzeppelin-contracts@4.4.2'

dotenv: .env
networks:
  default: development
  development:
    eth-usd-price-feed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
  mainnet-fork:
    eth-usd-price-feed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
    verify: False
  ganache-local:
    verify: False
  wallets:
    from-key: ${PRIVATE_KEY}